---
version: "3"
services:

  wordpress:
    image: wordpress:fpm
    hostname: wordpress
    networks:
      - proxy
      - db
    env_file:
      - ${SECRETSDIR}/${DOCKER_MACHINE_NAME}/wordpress.env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_NAME: wp
    volumes:
      - ${APPDATADIR}/data/wordpress:/var/www/html
      - ${APPDATADIR}/config/wordpress/php-local.ini:/usr/local/etc/php/conf.d/php-local.ini
    depends_on:
      - db
    restart: unless-stopped

  letsencrypt:
    image: linuxserver/letsencrypt
    hostname: letsencrypt
    networks:
      - proxy
    cap_add:
      - NET_ADMIN
    env_file:
      - ${SECRETSDIR}/${DOCKER_MACHINE_NAME}/letsencrypt.env
      - ${SECRETSDIR}/${DOCKER_MACHINE_NAME}/linuxserver.env
    volumes:
      - ${APPDATADIR}/data/wordpress:/var/www/html:ro
      - ${APPDATADIR}/config/letsencrypt:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  db:
    image: linuxserver/mariadb
    hostname: db
    networks:
      - db
    env_file:
      - ${SECRETSDIR}/${DOCKER_MACHINE_NAME}/db.env
      - ${SECRETSDIR}/${DOCKER_MACHINE_NAME}/linuxserver.env
    environment:
      - MYSQL_DATABASE=wp
      - MYSQL_USER=wp
    volumes:
      - ${APPDATADIR}/data/wordpress-db:/config
    restart: unless-stopped

  redis:
    image: redis:alpine
    hostname: redis
    networks:
      - proxy
    restart: unless-stopped

  ddclient:
    image: linuxserver/ddclient
    hostname: ddclient
    env_file:
      - ${SECRETSDIR}/${DOCKER_MACHINE_NAME}/linuxserver.env
    volumes:
      - ${APPDATADIR}/config/ddclient:/config
    restart: unless-stopped

networks:
  proxy:
  db:
