---
version: "3"
services:

  wordpress:
    image: wordpress:fpm
    hostname: wordpress
    networks:
      - web
      - db
    env_file:
      - ${SECRETSDIR}/${DOCKER_MACHINE_NAME}/wordpress.env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_NAME: wp
    volumes:
      - /mnt/${DOCKER_MACHINE_NAME}_wp:/var/www/html
      - ${APPDATADIR}/config/wordpress/php-local.ini:/usr/local/etc/php/conf.d/php-local.ini:ro
    depends_on:
      - db
    restart: unless-stopped

  web:
    image: nginx
    hostname: web
    networks:
      - web
    volumes:
      - /mnt/${DOCKER_MACHINE_NAME}_wp:/var/www/html:ro
      - ${APPDATADIR}/config/web/nginx-conf:/etc/nginx/conf.d:ro
      - ${APPDATADIR}/config/web/ssl:/etc/ssl:ro
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  db:
    image: mariadb
    hostname: db
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - db
    env_file:
      - ${SECRETSDIR}/${DOCKER_MACHINE_NAME}/db.env
    environment:
      - MYSQL_DATABASE=wp
      - MYSQL_USER=wp
    volumes:
      - /mnt/${DOCKER_MACHINE_NAME}_db:/var/lib/mysql
    restart: unless-stopped

  ddclient:
    image: linuxserver/ddclient
    hostname: ddclient
    env_file:
      - ${SECRETSDIR}/${DOCKER_MACHINE_NAME}/linuxserver.env
    volumes:
      - ${APPDATADIR}/config/ddclient:/config:ro
    restart: unless-stopped

networks:
  web:
  db:
